-- Tabla principal de Gastos
CREATE TABLE IF NOT EXISTS gastos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    hash TEXT UNIQUE NOT NULL,
    fecha DATE,
    comercio TEXT,
    monto DECIMAL,
    moneda TEXT DEFAULT 'CLP',
    categoria TEXT,
    estado TEXT DEFAULT 'Pendiente',
    foto_url TEXT,
    notas TEXT
);

-- Tabla de Aprendizaje para el sistema
CREATE TABLE IF NOT EXISTS aprendizaje (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patron TEXT UNIQUE NOT NULL,
    comercio_limpio TEXT NOT NULL,
    categoria_fija TEXT
);

-- Inserción de ejemplo para aprendizaje
INSERT INTO aprendizaje (patron, comercio_limpio, categoria_fija)
VALUES ('STARBUCKS', 'Starbucks', 'Restaurante/Café')
ON CONFLICT (patron) DO NOTHING;
